const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

  //user
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  USER_LOGIN_HOME_SUCCESS: 'USER_LOGIN_HOME_SUCCESS',
  USER_LOGIN_HOME_FAIL: 'USER_LOGIN_HOME_FAIL',
  PROCESS_HOME_LOGOUT: 'PROCESS_HOME_LOGOUT',

  //action- ADMIN
  //GENDER
  FETCH_GENDER_START: 'FETCH_GENDER_START',
  FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
  FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

  //ROLE
  FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
  FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

  //POSITION
  FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
  FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

  //create user
  INSERT_USER_SUCCESS: 'INSERT_USER_SUCCESS',
  INSERT_USER_FAILED: 'INSERT_USER_FAILED',

  //update user
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

  //read user
  READ_ALL_USER_SUCCESS: 'READ_ALL_USER_SUCCESS',
  READ_ALL_USER_FAILED: 'READ_ALL_USER_FAILED',

  //delete user
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILED: 'DELETE_USER_FAILED',

  //get doctor
  READ_LIMIT_DOCTOR_SUCCESS: 'READ_LIMIT_DOCTOR_SUCCESS',
  READ_LIMIT_DOCTOR_FAILED: 'READ_LIMIT_DOCTOR_FAILED',

  //get all doctor
  GET_DOCTOR_SUCCESS: 'GET_DOCTOR_SUCCESS',
  GET_DOCTOR_FAILED: 'GET_DOCTOR_FAILED',

  //save info doctor
  SAVE_DOCTOR_SUCCESS: 'SAVE_DOCTOR_SUCCESS',
  SAVE_DOCTOR_FAILED: 'SAVE_DOCTOR_FAILED',

  //get allcode schdeule
  GET_ALLCODE_SCHEDULE_SUCCESS: 'GET_ALLCODE_SCHEDULE_SUCCESS',
  GET_ALLCODE_SCHEDULE_FAILED: 'GET_ALLCODE_SCHEDULE_FAILED',

  //get schdeule
  GET_SCHEDULE_SUCCESS: 'GET_SCHEDULE_SUCCESS',
  GET_SCHEDULE_FAILED: 'GET_SCHEDULE_FAILED',

  //delete schedule
  DELETE_SCHEDULE_SUCCESS: 'DELETE_SCHEDULE_SUCCESS',
  DELETE_SCHEDULE_FAILED: 'DELETE_SCHEDULE_FAILED',

  //count schdeule
  COUNT_SCHEDULE_SUCCESS: 'COUNT_SCHEDULE_SUCCESS',
  COUNT_SCHEDULE_FAILED: 'COUNT_SCHEDULE_FAILED',

  //read specialty
  READ_SPECIALTY_SUCCESS: 'READ_SPECIALTY_SUCCESS',
  READ_SPECIALTY_FAILED: 'READ_SPECIALTY_FAILED',

  //read clinic
  READ_CLINIC_SUCCESS: 'READ_CLINIC_SUCCESS',
  READ_CLINIC_FAILED: 'READ_CLINIC_FAILED',

  //get data info doctor
  GET_DATA_INFO_DOCTOR_START: 'GET_DATA_INFO_DOCTOR_START',
  GET_DATA_INFO_DOCTOR_SUCCESS: 'GET_DATA_INFO_DOCTOR_SUCCESS',
  GET_DATA_INFO_DOCTOR_FAILED: 'GET_DATA_INFO_DOCTOR_FAILED',
});

export default actionTypes;
